service: AWS-Certification-Task-1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource:
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ordersTable
        - Effect: Allow
          Action:
            - kinesis:PutRecord
          Resource:
            - !Sub arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/order-events
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource:
            - "*"
          Condition:
            StringEquals:
              ses:FromAddress:
                - Yana_Bahdanovich@mail.ru
                - Yana_Bahdanovich@epam.com

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
    environment:
      orderTableName: ordersTable
      orderStreamName: order-events
  fulfillOrder:
    handler: handler.fulfillOrder
    events:
      - http:
          path: /order/fulfilled
          method: post
    environment:
      orderTableName: ordersTable
      orderStreamName: order-events
  notifyCakeMaker:
    handler: handler.notifyCakeMaker
    events:
      - stream:
          # does not support !Sub =(
          arn: arn:aws:kinesis:us-east-1:846910419469:stream/order-events
    environment:
      region: us-east-1
      orderingSystemEmail: Yana_Bahdanovich@mail.ru
      cakeMakerEmail: Yana_Bahdanovich@epam.com

resources:
  Resources:
    # CloudFormation stream name
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        # Kinesis stream name
        Name: order-events
        ShardCount: 1
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: "orderId"
            AttributeType: "S"
        # Define "orderId" as key
        KeySchema:
          - AttributeName: "orderId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
